In [1]:
# http://old.sebug.net/paper/books/scipydoc/numpy_intro.html
# http://blog.csdn.net/chen_shiqiang/article/details/51868115

指定 axis 参数你可以吧运算应用到数组指定的轴上：

In [3]:
from numpy import *
b=arange(12).reshape(3,4)
b.sum(axis=1)

array([ 6, 22, 38])

In [4]:
print(b)
print(b.min(axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 4 8]


In [9]:
print(b.min(axis=0))

[0 1 2 3]


In [10]:
b.min()

0

In [11]:
b.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66], dtype=int32)

In [12]:
b.cumsum(axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]], dtype=int32)

In [13]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

ufunc

In [16]:
# https://docs.scipy.org/doc/numpy/reference/routines.html
import requests
a=requests.get('https://docs.scipy.org/doc/numpy/reference/routines.html')

想对每个数组中元素进行运算，我们可以使用flat属性

In [17]:
for element in b.flat:
    print(element)

0
1
2
3
4
5
6
7
8
9
10
11


一个数组的形状可以被多种命令修改：

In [18]:
a=floor(10*random.random((3,4)))
a

array([[ 4.,  4.,  3.,  6.],
       [ 3.,  9.,  6.,  1.],
       [ 4.,  3.,  6.,  4.]])

In [19]:
a.ravel()

array([ 4.,  4.,  3.,  6.,  3.,  9.,  6.,  1.,  4.,  3.,  6.,  4.])

In [22]:
a.shape=(6,2)
a

array([[ 4.,  4.],
       [ 3.,  6.],
       [ 3.,  9.],
       [ 6.,  1.],
       [ 4.,  3.],
       [ 6.,  4.]])

In [23]:
a.transpose()

array([[ 4.,  3.,  3.,  6.,  4.,  6.],
       [ 4.,  6.,  9.,  1.,  3.,  4.]])

stack

In [25]:
a=floor(10*random.random((2,2)))
b=floor(10*random.random((2,2)))
vstack((a,b))

array([[ 0.,  1.],
       [ 4.,  4.],
       [ 8.,  4.],
       [ 6.,  4.]])

In [26]:
hstack((a,b))

array([[ 0.,  1.,  8.,  4.],
       [ 4.,  4.,  6.,  4.]])